package: niworkflows
sections:
- name: Summary
  reportlets:
  - bids: {datatype: figures, desc: summary, suffix: T1w}
- name: Anatomical
  reportlets:
  - bids:
      datatype: figures
      desc: conform
      extension: [.html]
      suffix: T1w
  - bids: {datatype: figures, suffix: dseg}
    caption: This panel shows the template T1-weighted image (if several T1w images
      were found), with contours delineating the detected brain mask and brain tissue
      segmentations.
    subtitle: Brain mask and brain tissue segmentation of the T1w
  - bids: {datatype: figures, space: .*, suffix: T1w, regex_search: True}
    caption: Spatial normalization of the T1w image to the <code>{space}</code> template.
    description: Results of nonlinear alignment of the T1w reference one or more template
      space(s). Hover on the panels with the mouse pointer to transition between both
      spaces.
    static: false
    subtitle: Spatial normalization of the anatomical T1w reference
  - bids: {datatype: figures, desc: reconall, suffix: T1w}
    caption: Surfaces (white and pial) reconstructed with FreeSurfer (<code>recon-all</code>)
      overlaid on the participant's T1w template.
    subtitle: Surface reconstruction

- name: <em>B<sub>0</sub></em> field mapping
  ordering: session,acquisition,reconstruction,direction,run,fmapid
  reportlets:
  - bids: {datatype: figures, desc: mapped, suffix: fieldmap}
    caption: Inhomogeneities of the <em>B<sub>0</sub></em> field introduce (oftentimes severe) spatial distortions
      along the phase-encoding direction of the image. Some scanners produce a <em>B<sub>0</sub></em>
      mapping of the field, using Spiral Echo Imaging (SEI) or postprocessing a "phase-difference"
      acquisition. The plot below shows an anatomical "magnitude" reference and the corresponding
      fieldmap.
    description: Hover over the panels with the mouse pointer to also visualize the intensity of the
      field inhomogeneity in Hertz.
    static: false
    subtitle: "Preprocessed <em>B<sub>0</sub></em> mapping acquisition"
  - bids: {datatype: figures, desc: phasediff, suffix: fieldmap}
    caption: Inhomogeneities of the <em>B<sub>0</sub></em> field introduce (oftentimes severe) spatial distortions
      along the phase-encoding direction of the image. A Gradient-Recalled Echo (GRE) scheme for the
      mapping of the <em>B<sub>0</sub></em> inhomogeneities by subtracting the phase maps obtained at
      two subsequent echoes. The plot below shows an anatomical "magnitude" reference and the corresponding
      fieldmap.
    description: Hover over the panels with the mouse pointer to also visualize the intensity of the
      field inhomogeneity in Hertz.
    static: false
    subtitle: "Preprocessed mapping of phase-difference acquisition"
  - bids: {datatype: figures, desc: pepolar, suffix: fieldmap}
    caption: Inhomogeneities of the <em>B<sub>0</sub></em> field introduce (oftentimes severe) spatial distortions
      along the phase-encoding direction of the image. Utilizing two or more images with different
      phase-encoding polarities (PEPolar) or directions, it is possible to estimate the inhomogeneity
      of the field. The plot below shows a reference EPI (echo-planar imaging) volume generated
      using two or more EPI images with varying phase-encoding blips.
    description: Hover on the panels with the mouse pointer to also visualize the intensity of the
      inhomogeneity of the field in Hertz.
    static: false
    subtitle: "Preprocessed estimation with varying Phase-Endocing (PE) blips"
  - bids: {datatype: figures, desc: anat, suffix: fieldmap}
    caption: Inhomogeneities of the <em>B<sub>0</sub></em> field introduce (oftentimes severe) spatial distortions
      along the phase-encoding direction of the image. Utilizing an <em>anatomically-correct</em> acquisition
      (for instance, T1w or T2w), it is possible to estimate the inhomogeneity of the field by means of nonlinear
      registration. The plot below shows a reference EPI (echo-planar imaging) volume generated
      using two or more EPI images with the same PE encoding, after alignment to the anatomical scan.
    description: Hover on the panels with the mouse pointer to also visualize the intensity of the
      inhomogeneity of the field in Hertz.
    static: false
    subtitle: "Preprocessed estimation by nonlinear registration to an anatomical scan (&ldquo;<em>fieldmap-less</em>&rdquo;)"

- name: Functional
  ordering: session,task,acquisition,ceagent,reconstruction,direction,run,echo
  reportlets:
  - bids: {datatype: figures, desc: summary, suffix: bold}
  - bids: {datatype: figures, desc: validation, suffix: bold}
  - bids: {datatype: figures, desc: magnitude, suffix: bold}
    caption: Results of affine coregistration between the magnitude image of the fieldmap
      and the reference EPI image
    static: false
    subtitle: Fieldmap to EPI registration
  - bids: {datatype: figures, desc: fieldmap, suffix: bold}
    caption: Overlaid on the reference EPI image.
    static: false
    subtitle: Fieldmap
  - bids: {datatype: figures, desc: sdc, suffix: bold}
    caption: Results of performing susceptibility distortion correction (SDC) on the
      EPI
    static: false
    subtitle: Susceptibility distortion correction
  - bids: {datatype: figures, desc: forcedsyn, suffix: bold}
    caption: The dataset contained some fieldmap information, but the argument <code>--force-syn</code>
      was used. The higher-priority SDC method was used. Here, we show the results
      of performing SyN-based SDC on the EPI for comparison.
    static: false
    subtitle: Experimental fieldmap-less susceptibility distortion correction
  - bids: {datatype: figures, desc: flirtnobbr, suffix: bold}
    caption: FSL <code>flirt</code> was used to generate transformations from EPI
      space to T1 Space - BBR refinement rejected. Note that Nearest Neighbor interpolation
      is used in the reportlets in order to highlight potential spin-history and other
      artifacts, whereas final images are resampled using Lanczos interpolation.
    static: false
    subtitle: Alignment of functional and anatomical MRI data (volume based)
  - bids: {datatype: figures, desc: coreg, suffix: bold}
    caption: <code>mri_coreg</code> (FreeSurfer) was used to generate transformations
      from EPI space to T1 Space - <code>bbregister</code> refinement rejected. Note
      that Nearest Neighbor interpolation is used in the reportlets in order to highlight
      potential spin-history and other artifacts, whereas final images are resampled
      using Lanczos interpolation.
    static: false
    subtitle: Alignment of functional and anatomical MRI data (volume based)
  - bids: {datatype: figures, desc: flirtbbr, suffix: bold}
    caption: FSL <code>flirt</code> was used to generate transformations from EPI-space
      to T1w-space - The white matter mask calculated with FSL <code>fast</code> (brain
      tissue segmentation) was used for BBR. Note that Nearest Neighbor interpolation
      is used in the reportlets in order to highlight potential spin-history and other
      artifacts, whereas final images are resampled using Lanczos interpolation.
    static: false
    subtitle: Alignment of functional and anatomical MRI data (surface driven)
  - bids: {datatype: figures, desc: bbregister, suffix: bold}
    caption: <code>bbregister</code> was used to generate transformations from EPI-space
      to T1w-space. Note that Nearest Neighbor interpolation is used in the reportlets
      in order to highlight potential spin-history and other artifacts, whereas final
      images are resampled using Lanczos interpolation.
    static: false
    subtitle: Alignment of functional and anatomical MRI data (surface driven)
  - bids: {datatype: figures, desc: rois, suffix: bold}
    caption: Brain mask calculated on the BOLD signal (red contour), along with the
      masks used for a/tCompCor.<br />The aCompCor mask (magenta contour) is a conservative
      CSF and white-matter mask for extracting physiological and movement confounds.
      <br />The fCompCor mask (blue contour) contains the top 5% most variable voxels
      within a heavily-eroded brain-mask.
    subtitle: Brain mask and (temporal/anatomical) CompCor ROIs
  - bids:
      datatype: figures
      desc: '[at]compcor'
      extension: [.html]
      suffix: bold
  - bids: {datatype: figures, desc: 'compcorvar', suffix: bold}
    caption: The cumulative variance explained by the first k components of the
      <em>t/aCompCor</em> decomposition, plotted for all values of <em>k</em>.
      The number of components that must be included in the model in order to
      explain some fraction of variance in the decomposition mask can be used
      as a feature selection criterion for confound regression.
    subtitle: Variance explained by t/aCompCor components
  - bids: {datatype: figures, desc: carpetplot, suffix: bold}
    caption: Summary statistics are plotted, which may reveal trends or artifacts
      in the BOLD data. Global signals calculated within the whole-brain (GS), within
      the white-matter (WM) and within cerebro-spinal fluid (CSF) show the mean BOLD
      signal in their corresponding masks. DVARS and FD show the standardized DVARS
      and framewise-displacement measures for each time point.<br />A carpet plot
      shows the time series for all voxels within the brain mask. Voxels are grouped
      into cortical (blue), and subcortical (orange) gray matter, cerebellum (green)
      and white matter and CSF (red), indicated by the color map on the left-hand
      side.
    subtitle: BOLD Summary
  - bids: {datatype: figures, desc: 'confoundcorr', suffix: bold}
    caption: |
      Left: Heatmap summarizing the correlation structure among confound variables.
      (Cosine bases and PCA-derived CompCor components are inherently orthogonal.)
      Right: magnitude of the correlation between each confound time series and the
      mean global signal. Strong correlations might be indicative of partial volume
      effects and can inform decisions about feature orthogonalization prior to
      confound regression.
    subtitle: Correlations among nuisance regressors
  - bids: {datatype: figures, desc: aroma, suffix: bold}
    caption: |
      Maps created with maximum intensity projection (glass brain) with a
      black brain outline. Right hand side of each map: time series (top in seconds),
      frequency spectrum (bottom in Hertz). Components classified as signal are plotted
      in green; noise components in red.
    subtitle: ICA Components classified by AROMA
- name: About
  reportlets:
  - bids: {datatype: figures, desc: about, suffix: T1w}
