
name: Build docs

on:
  pull_request:
    branches: [ master, 'maint/*' ]

jobs:
  build:
    if: "(github.repository_owner != 'nipreps') && !contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Determine current branch/tag name
      run: |
        if [[ "$GITHUB_REF" == refs/pull/* ]]; then
          CURBRANCH=${GITHUB_REF%/*}
          CURBRANCH=${CURBRANCH##*/}
        elif [[ "$GITHUB_REF" == refs/heads/* ]]; then
          CURBRANCH=${GITHUB_REF##*/}
        elif [[ "$GITHUB_REF" == refs/tags/* ]]; then
          echo "This build should not be picking up a tag, cancelling."
          exit 1
        fi

        # Remove forward slashes
        CURBRANCH=$( echo $CURBRANCH | sed 's+/+_+g' )
        echo "Building branch/tag ${CURBRANCH:-<unkwown>}, from git ref <$GITHUB_REF>"
        echo "CURBRANCH=${CURBRANCH}" >> ${GITHUB_ENV}

    - name: Install GraphViz
      run: |
        sudo apt-get update -y
        sudo apt-get install -y --no-install-recommends graphviz

    - name: Install dependencies
      run: |
        pip install -r docs/requirements.txt

    - name: Build docs
      run: |
          make -C docs/ SPHINXOPTS="-W" BUILDDIR="$HOME/docs" OUTDIR="${CURBRANCH:-html}" html
